### model
model_name_or_path: /home/agent_h/data/data_new/llms/Qwen2-VL-2B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: lrs3_v2
template: qwen2_vl
cutoff_len: 1024
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/agent_h/data/data_new/llms-exp/03_qwen2vl_full_sft_half_face_56
logging_steps: 100
save_steps: 3000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 30.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 3000
